[2019-03-04 23:43:43,315]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:54} WARNING - REQUEST LOG	{"request": {"username": "rizky", "password": "passrizky", "email": "rizky@gmial.com", "role": "customer"}, "response": {"message": {"username": "Missing required parameter in the query string"}}}
[2019-03-04 23:47:50,447]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:54} WARNING - REQUEST LOG	{"request": {"username": "rizky", "password": "passrizky", "email": "rizky@gmial.com", "role": "customer"}, "response": {"message": {"username": "Missing required parameter in the query string"}}}
[2019-03-04 23:49:28,036]{/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /customer [POST]
Traceback (most recent call last):
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/customer/resource.py", line 77, in post
    customers = Customers(None, args['username'],args['password'], args['email'], args['role'])
TypeError: __init__() missing 1 required positional argument: 'role'
[2019-03-04 23:49:28,039]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:54} WARNING - REQUEST LOG	{"request": {"username": "rizky", "password": "passrizky", "email": "rizky@gmial.com", "role": "customer"}, "response": {"message": "Internal Server Error"}}
[2019-03-04 23:50:56,664]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:54} WARNING - REQUEST LOG	{"request": {"username": "rizky", "password": "passrizky", "email": "rizky@gmial.com"}, "response": {"message": {"phone": "Missing required parameter in the JSON body"}}}
[2019-03-04 23:51:11,999]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:54} WARNING - REQUEST LOG	{"request": {"username": "rizky", "password": "passrizky", "email": "rizky@gmial.com", "role": "customer"}, "response": {"message": {"phone": "Missing required parameter in the JSON body"}}}
[2019-03-04 23:51:33,527]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:54} WARNING - REQUEST LOG	{"request": {"username": "rizky", "password": "passrizky", "email": "rizky@gmial.com", "phone": "08221313"}, "response": {"client_id": 1, "username": "rizky", "password": "passrizky", "phone": "rizky@gmial.com", "email": "08221313", "role": "customer"}}
[2019-03-04 23:52:10,331]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:47} WARNING - REQUEST LOG	{"request": {}, "response": {"message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."}}
[2019-03-04 23:52:22,231]{/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /customer [GET]
Traceback (most recent call last):
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/customer/resource.py", line 20, in get
    qry = Customer.query.get(customer['id'])
NameError: name 'Customer' is not defined
[2019-03-04 23:52:22,234]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:47} WARNING - REQUEST LOG	{"request": {}, "response": {"message": "Internal Server Error"}}
[2019-03-04 23:52:24,668]{/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /customer [GET]
Traceback (most recent call last):
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/customer/resource.py", line 20, in get
    qry = Customer.query.get(customer['id'])
NameError: name 'Customer' is not defined
[2019-03-04 23:52:24,669]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:47} WARNING - REQUEST LOG	{"request": {}, "response": {"message": "Internal Server Error"}}
[2019-03-04 23:53:07,744]{/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /customer [GET]
Traceback (most recent call last):
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/customer/resource.py", line 20, in get
    qry = Customers.query.get(customer['id'])
KeyError: 'id'
[2019-03-04 23:53:07,747]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:47} WARNING - REQUEST LOG	{"request": {}, "response": {"message": "Internal Server Error"}}
[2019-03-04 23:53:09,180]{/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /customer [GET]
Traceback (most recent call last):
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/env_pf/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/customer/resource.py", line 20, in get
    qry = Customers.query.get(customer['id'])
KeyError: 'id'
[2019-03-04 23:53:09,181]{/home/alphatech/Documents/E-Commerce/portofolio/Portofolio/blueprint/__init__.py:47} WARNING - REQUEST LOG	{"request": {}, "response": {"message": "Internal Server Error"}}
